---
server:
  port: 8080
  contextPath: /SpringBootCRUDApp
---
spring:
  profiles:
    active: "dev"
  main:
    banner-mode: "off"

server:
  email: jacquesns@gmail.com

---
spring:
  profiles: local
datasource:
  sampleapp:
    url: jdbc:h2:~/test
    username: SA
    password:
    driverClassName: org.h2.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: create-drop
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.H2Dialect
---
spring:
  profiles: dev
datasource:
  sampleapp: 
    url: jdbc:postgresql://localhost:5432/testing
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect

